export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const RECEIVED_USER_STATUS = 'RECEIVED_USER_STATUS';
export const RECEIVED_USER_STATUS_ERROR = 'RECEIVED_USER_STATUS_ERROR';
export const REQUEST_PASSWORD_UPDATE = 'REQUEST_PASSWORD_UPDATE';
export const RECEIVED_PASSWORD_UPDATE = 'RECEIVED_PASSWORD_UPDATE';
