let strings = ({
    "en": {
        checkIn: "Check In",
        checkedText: "Checked In Asset",
        checkedInUserText: "CheckedIn User",
        checkOut: "Check Out",
        taskButton: "TASKS",
        gasFillButton: "GAS FILL UP",
        homeTitle: "Welcome To My FMS",
        mileageButton: "UPDATE MILEAGE",
        mileageLabel: "Mileage",
        serviceButton: "SERVICE TICKET",
        documentButton: "DOCUMENTS",
        contactButton: "CONTACT MECHANIC",
        languageSelection: "Preferred Language",
        assetId: "Asset Id: ",
        make: "Make",
        fuelType: "Fuel Type",
        model: "Model",
        engineDisplacement: "Engine Displacement",
        odometerHelperText: "Use Camera to take Picture of Odometer",
        saveButton: "Save",
        gasFillUpTitle: "Gas Fill Up",
        volumeLabel: "Volume",
        amountLabel: "Amount",
        goToCamera: "Go To Camera",
        gasHelperText: "Take a picture of the fuel Pump Display after completing fill up. The display Should show gallons and sales amount. Make sure that there is no sun glare or reflection off the display when taking the photo.",
        invalidDocType: "INVALID DOCUMENT TYPE",
        titleDoc: "TITLE DOCUMENT",
        insuranceDoc: "INSURANCE DOCUMENT",
        registrationDoc: "REGISTRATION DOCUMENT",
        inspectionDoc: "INSPECTION CERTIFICATE",
        uploadSuccessMsg: "Document Uploaded Successfully.",
        saveSuccessMsg: "Saved Successfully.",
        assetFetchSuccMsg: "Asset Fetched Successfully.",
        checkInSuccessMsg: "Checked In Successfully.",
        docFetchSuccessMsg: "Documents Retrieved Successfully.",
        emailLabel: "Email",
        passwordLabel: "Password",
        loginLabel: "LOGIN",
        signupText: "Request For Sign Up",
        "securitySettingsTitle": "Security Settings",
        "changePasswordTitle": "Change Password",
        "appLockTitle": "Manage App Lock",
        "manageLanguageTitle": "Manage Language",
        "userAccountTitle": "User Account",
        "logoutTitle": "LOGOUT",
        "oldPasswordLabel": "Old Password",
        "newPasswordLabel": "New Password",
        "confirmPasswordLabel": "Confirm Password",
        "passwordErrorText": "Invalid Password. Atleast 4 digits.",
        "confirmPasswordErrorText": "Confirm password should match with new password.",
        "expenseReportTitle": "Expense Report",
        "expenseLabel": "Expense Amount",
        "expenseErrorText": "Amount should be greater than 0",
        "confirmExpenseLabel": "Confirm Expense Amount",
        "confExpenseErrorText": "Both Amount should match.",
        "uploadInvoiceTitle": "Upload Invoice/ Document",

        "uploadTitle": "Upload Documents",
        "spanishTitle": "Spanish",
        "englishTitle": "English",
        "proceedText": "PROCEED",
        "selectLanguageTitle": "Select Language",
        "HOME": "HOME",
        "TASKS": "TASKS",
        "SERVICES": "SERVICES",
        "CONTACT": "CONTACT",
        "SETTINGS": "SETTINGS",
    },
    spn: {
        checkIn: "Registrarse",
        checkedText: "Activo registrado",
        checkedInUserText: "Usuario registrado",
        checkOut: "Revisa",
        taskButton: "TAREAS",
        gasFillButton: "RELLENO DE GAS",
        homeTitle: "Bienvenido A Mi FMS",
        mileageButton: "ACTUALIZAR MILLAJE",
        mileageLabel: "Kilometraje",
        serviceButton: "BOLETO DE SERVICIO",
        documentButton: "DOCUMENTOS",
        contactButton: "CONTACTO MECANICO",
        languageSelection: "Idioma preferido",
        assetId: "Identificación del activo: ",
        make: "Hacer",
        fuelType: "Tipo de combustible",
        model: "Modelo",
        engineDisplacement: "Desplazamiento del motor",
        odometerHelperText: "Usa la cámara para tomar una foto del odómetro",
        saveButton: "Salvar",
        gasFillUpTitle: "Llenado de gas",
        volumeLabel: "Volumen",
        amountLabel: "Cantidad",
        goToCamera: "Ir a la camara",
        gasHelperText: "Tome una fotografía de la pantalla de la bomba de combustible después de completar el llenado. La pantalla debe mostrar galones y cantidad de ventas. Al tomar la foto, asegúrese de que no haya reflejos ni reflejos en la pantalla.",
        invalidDocType: "TIPO DE DOCUMENTO NO VÁLIDO",
        titleDoc: "TITLE DOCUMENT",
        insuranceDoc: "DOCUMENTO DE TITULOS",
        registrationDoc: "DOCUMENTO DE REGISTRO",
        inspectionDoc: "CERTIFICADO DE INSPECCIÓN",
        uploadSuccessMsg: "Documento subido con éxito.",
        saveSuccessMsg: "Guardado exitosamente.",
        assetFetchSuccMsg: "Activo Fetched con éxito.",
        checkInSuccessMsg: "Registrado con éxito.",
        docFetchSuccessMsg: "Documentos recuperados con éxito.",
        emailLabel: "Email",
        passwordLabel: "Contraseña",
        loginLabel: "INICIAR SESIÓN",
        signupText: "Solicitud de registro",
        "securitySettingsTitle": "Configuraciones de seguridad",
        "changePasswordTitle": "Cambia la contraseña",
        "appLockTitle": "Administrar el bloqueo de la aplicación",
        "manageLanguageTitle": "Manejar el idioma",
        "userAccountTitle": "Cuenta de usuario",
        "logoutTitle": "CERRAR SESIÓN",
        "oldPasswordLabel": "Contraseña anterior",
        "newPasswordLabel": "Nueva contraseña",
        "confirmPasswordLabel": "Confirmar contraseña",
        "passwordErrorText": "Contraseña invalida. Al menos 4 dígitos.",
        "confirmPasswordErrorText": "Confirmar contraseña debe coincidir con la nueva contraseña.",
        "expenseReportTitle": "Informe de gastos",
        "expenseLabel": "Cantidad de gastos",
        "expenseErrorText": "La cantidad debe ser mayor que 0",
        "confirmExpenseLabel": "Confirmar la cantidad de gastos",
        "confExpenseErrorText": "Ambas cantidades deben coincidir.",
        "uploadTitle": "subir documentos",
        "spanishTitle": "Español",
        "englishTitle": "Inglés",
        "proceedText": "PROCEDER",
        "selectLanguageTitle": "Seleccione el idioma",
        "uploadInvoiceTitle": "Cargar factura / documento",
        "HOME": "CASA",
        "TASKS": "TAREAS",
        "SERVICES": "SERVICIOS",
        "CONTACT": "CONTACTO",
        "SETTINGS": "AJUSTES",
    }
});

export default strings;