let strings = ({ 
"supportedLanguages": [
    {"displayText":  "English", "value": "en"}, {"displayText":  "Spanish", "value": "spn"}
],
"bundle": {
  "en": {
    "clockIn": "Clock In",
    "clockedText": "Clocked In Asset",
    "clockedInUserText": "ClockedIn User",
    "clockOut": "Clock Out",
    "taskButton": "Tasks/ To Do",
    "gasFillButton": "Fuel Fill Up",
    "homeTitle": "Welcome To My FMS",
    "mileageButton": "Update Miles",
    "mileageLabel": "Miles",
    "serviceButton": "Service Ticket",
    "documentButton": "Documents",
    "contactButton": "Contact FM/ Mechanic",
    "languageSelection": "Preferred Language",
    "assetId": "Asset Id: ",
    "make": "Make",
    "fuelType": "Fuel Type",
    "model": "Model",
    "engineDisplacement": "Engine Displacement",
    "odometerHelperText": "Use Camera to take Picture of Odometer",
    "saveButton": "Save",
    "gasFillUpTitle": "Fuel Fill Up",
    "volumeLabel": "Volume",
    "amountLabel": "Amount",
    "goToCamera": "Go To Camera",
    "gasHelperText": "Take a picture of your fuel fill up receipt. Make sure it is clear and not blurry.",
    "mileageHelperText": "Take a picture of your odometer. Make sure it is clear and not blurry.",
    
    "invalidDocType": "INVALID DOCUMENT TYPE",
    "titleDoc": "TITLE DOCUMENT",
    "insuranceDoc": "INSURANCE DOCUMENT",
    "registrationDoc": "REGISTRATION DOCUMENT",
    "inspectionDoc": "INSPECTION CERTIFICATE",
    "uploadSuccessMsg": "Document Uploaded Successfully.",
    "saveSuccessMsg": "Saved Successfully.",
    "assetFetchSuccMsg": "Asset Fetched Successfully.",
    "clockInSuccessMsg": "Clocked In Successfully.",
    "docFetchSuccessMsg": "Documents Retrieved Successfully.",
    "emailLabel": "Email",
    "passwordLabel": "Password",
    "loginLabel": "LOGIN",
    "signupText": "Request For Sign Up",
    "securitySettingsTitle": "Security Settings",
    "changePasswordTitle": "Change Password",
    "appLockTitle": "Manage App Lock",
    "manageLanguageTitle": "Manage Language",
    "userAccountTitle": "User Account",
    "logoutTitle": "LOGOUT",
    "oldPasswordLabel": "Old Password",
    "newPasswordLabel": "New Password",
    "confirmPasswordLabel": "Confirm Password",
    "passwordErrorText": "Invalid Password. Atleast 4 digits.",
    "confirmPasswordErrorText": "Confirm password should match with new password.",
    "expenseReportTitle": "Upload Invoice",
    "expenseLabel": "Expense Amount",
    "expenseErrorText": "Amount should be greater than 0",
    "confirmExpenseLabel": "Confirm Expense Amount",
    "confExpenseErrorText": "Both Amount should match.",
    "uploadInvoiceTitle": "Upload Invoice/ Document",

    "uploadTitle": "Upload Documents",
    "spanishTitle": "Spanish",
    "englishTitle": "English",
    "proceedText": "PROCEED",
    "selectLanguageTitle": "Select Language",
    "HOME": "HOME",
    "TASKS": "TASKS",
    "SERVICES": "SERVICES",
    "CONTACT": "CONTACT",
    "SETTINGS": "SETTINGS",
    "customerSupport": "In case of login issues, please contact your manager. ",
    "confirmTitle": "Confirmation",
    "clockOutMsg": "Are you sure you want to clock out?",
    "confirmText": "Confirm",
    "clockInHelperText": "This will start your daily time sheet. Clock in only when ready.",
    "nextText": "NEXT",
    "expenseHelperText": "Take a picture of the full document – one photo for every page – and upload. Make sure each image is clear and not blurry.",
    "expenseAmountHelperText": "Input total amount of invoice and confirm. Enter amount as xx.xx – no $ sign or text required.",
    "openNewTicketLabel": "Open New Ticket",
    "reviewOpenTicketsLabel": "Review Open Tickets",
    "closedTicketsLabel": "Closed Tickets",
    "approvedTicketsLabel": "Approved Tickets",
    "rejectedTicketsLabel": "Rejected Tickets",
    "upcomingAppointmentsLabel": "Upcoming Appointments",
    "contactManagerLabel": "Contact Fleet Manager",
    "otherRepairReqTitle": "Service Ticket Request",
    "notesLabel": "Notes: (as detailed as possible)",
    "reviewLabel": "Review",
    "commentsTitle": "Comments",
    "cancelText": "Cancel",
    "addCommentText": "Add Comment",
    "noCommentsTitle": "No Comments Yet",
    "completeText": "Complete",
    "destinationText": "Mechanic",
    "dailyCheckList": "Daily Check List",
    "ticketIdLabel": "Ticket Id",
    "taskIdLabel": "Task Id",
    "rewardPointsLabel": "My Reward Points",
    "assetTitle": "Assets",
    "warning": "Warning",
    "pleaseFillNotesFieldToSave": "Please fill Notes field to Save.",
    "majorService": "Major Service",
    "ticketCommentAddedSuccessfully": "Ticket Comment Added Successfully.",
    "areYouSureYouWantToCancelThisTicket": "Are you sure you want to Cancel this ticket?",
    "doYouWantToApproveitOrRejectit?": "Do You Want To Approve it Or Reject it?",
    "ticketCancelledSuccessfully": "Ticket Cancelled Successfully",
    "dailyTasks": "Daily Tasks",
    "checkListSavedSuccessfully": "Check List Saved Successfully",
    "scheduleMaintainance": "Schedule Maintainance",
    "serviceTicket": "Service Ticket",
    "description": "Description",
    "wantToSendToServiceProvider": "Want to send to Service Provider",
    "newTask": "New Task",
    "comment": "Comment",
    "add": "Add",
    "taskList": "Task List"
  },
  "spn": {
    "clockIn": "Reloj en",
    "clockedText": "Registrado en el activo",
    "clockedInUserText": "Usuario ClockedIn",
    "clockOut": "Salida del reloj",
    "taskButton": "Tareas/ Que hacer",
    "gasFillButton": "Llenado de combustible",
    "homeTitle": "Bienvenido A Mi FMS",
    "mileageButton": "Millas de actualización",
    "mileageLabel": "Millas",
    "serviceButton": "Boleto de servicio",
    "documentButton": "Documentos",
    "contactButton": "Contacto FM/ Mecánico",
    "languageSelection": "Idioma preferido",
    "assetId": "Identificación del activo: ",
    "make": "Hacer",
    "fuelType": "Tipo de combustible",
    "model": "Modelo",
    "engineDisplacement": "Desplazamiento del motor",
    "odometerHelperText": "Usa la cámara para tomar una foto del odómetro",
    "saveButton": "Salvar",
    "gasFillUpTitle": "Llenado de combustible",
    "volumeLabel": "Volumen",
    "amountLabel": "Cantidad",
    "goToCamera": "Ir a la camara",
    "gasHelperText": "Tome una foto de su recibo de llenado de combustible. Asegúrate de que esté claro y no borroso.",
    "invalidDocType": "TIPO DE DOCUMENTO NO VÁLIDO",
    "titleDoc": "TITLE DOCUMENT",
    "insuranceDoc": "DOCUMENTO DE TITULOS",
    "registrationDoc": "DOCUMENTO DE REGISTRO",
    "inspectionDoc": "CERTIFICADO DE INSPECCIÓN",
    "uploadSuccessMsg": "Documento subido con éxito.",
    "saveSuccessMsg": "Guardado exitosamente.",
    "assetFetchSuccMsg": "Activo Fetched con éxito.",
    "clockInSuccessMsg": "Se registró con éxito.",
    "docFetchSuccessMsg": "Documentos recuperados con éxito.",
    "emailLabel": "Email",
    "passwordLabel": "Contraseña",
    "loginLabel": "INICIAR SESIÓN",
    "signupText": "Solicitud de registro",
    "securitySettingsTitle": "Configuraciones de seguridad",
    "changePasswordTitle": "Cambia la contraseña",
    "appLockTitle": "Administrar el bloqueo de la aplicación",
    "manageLanguageTitle": "Manejar el idioma",
    "userAccountTitle": "Cuenta de usuario",
    "logoutTitle": "CERRAR SESIÓN",
    "oldPasswordLabel": "Contraseña anterior",
    "newPasswordLabel": "Nueva contraseña",
    "confirmPasswordLabel": "Confirmar contraseña",
    "passwordErrorText": "Contraseña invalida. Al menos 4 dígitos.",
    "confirmPasswordErrorText": "Confirmar contraseña debe coincidir con la nueva contraseña.",
    "expenseReportTitle": "Cargar factura",
    "expenseLabel": "Cantidad de gastos",
    "expenseErrorText": "La cantidad debe ser mayor que 0",
    "confirmExpenseLabel": "Confirmar la cantidad de gastos",
    "confExpenseErrorText": "Ambas cantidades deben coincidir.",
    "uploadTitle": "subir documentos",
    "spanishTitle": "Español",
    "englishTitle": "Inglés",
    "proceedText": "PROCEDER",
    "selectLanguageTitle": "Seleccione el idioma",
    "uploadInvoiceTitle": "Cargar factura / documento",
    "HOME": "CASA",
    "TASKS": "TAREAS",
    "SERVICES": "SERVICIOS",
    "CONTACT": "CONTACTO",
    "SETTINGS": "AJUSTES",
    "customerSupport": "En caso de problemas de inicio de sesión, póngase en contacto con su administrador. ",
    "confirmTitle": "Confirmación",
    "clockOutMsg": "¿Estás seguro de que quieres salir?",
    "confirmText": "Confirmar",
    "clockInHelperText": "Esto comenzará su hoja de horas diaria. Registre solo cuando esté listo.",
    "mileageHelperText": "Tome una fotografía de su odómetro. Asegúrese de que esté claro y no borroso.",
    "nextText": "SIGUIENTE",
    "expenseHelperText": "Tome una fotografía del documento completo (una foto para cada página) y cárguela. Asegúrese de que cada imagen sea clara y no borrosa.",
    "expenseAmountHelperText": "Ingrese el importe total de la factura y confirme. Ingrese la cantidad como xx.xx - no se requiere $ signo o texto.",
    "openNewTicketLabel": "Abrir nuevo ticket",
    "reviewOpenTicketsLabel": "Revisar entradas abiertas",
    "closedTicketsLabel": "Entradas Cerradas",
    "approvedTicketsLabel": "Boletos aprobados",
    "rejectedTicketsLabel": "Boletos rechazados",
    "upcomingAppointmentsLabel": "Próximas citas",
    "contactManagerLabel": "Contacta a Fleet Manager",
    "otherRepairReqTitle": "Otra solicitud de reparación",
    "notesLabel": "Notas: (lo más detallado posible)",
    "reviewLabel": "revisión",
    "commentsTitle": "Comentarios",
    "cancelText": "Cancelar",
    "addCommentText": "Agregar comentario",
    "noCommentsTitle": "Sin comentarios aún",
    "completeText": "Completar",
    "destinationText": "Mecánico",
    "dailyCheckList": "Lista de verificación diaria",
    "ticketIdLabel": "Identificación de entradas",
    "taskIdLabel": "ID de tarea",
    "rewardPointsLabel": "Mis puntos de recompensa",
    "assetTitle": "Bienes",
    "warning": "Advertencia",
    "pleaseFillNotesFieldToSave": "Por favor, rellene el campo Notas para guardar",
    "majorService": "Servicio mayor",
    "ticketCommentAddedSuccessfully": "Comentario del boleto agregado exitosamente.",
    "areYouSureYouWantToCancelThisTicket": "Seguro que quieres cancelar este ticket?",
    "doYouWantToApproveitOrRejectit": "Quieres aprobarlo o rechazarlo?",
    "ticketCancelledSuccessfully": "Ticket Cancelled Successfully",
    "dailyTasks": "Tareas diarias",
    "checkListSavedSuccessfully": "Lista de verificación guardada con éxito",
    "scheduleMaintainance": "Mantenimiento de horario",
    "serviceTicket": "Boleto de servicio",
    "Description": "Descripción",
    "wantToSendToServiceProvider": "Quiere enviar al proveedor de servicios",
    "newTask": "Nueva tarea",
    "comment": "Comentario",
    "add": "Añadir",
    "taskList": "Lista de tareas"
  }
}
}
);

export default strings;